### ISSUE TITLE
make release command : ignore some directories and/or files

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfdata#241]
It would be nice to be able to ignore some directories or files when building a plugin with the make release command.

For instance, let's assume there is a 'tests' directory which contains  python unit test scripts with test data. When we want to deploy the application in a production environment , we don't want these elements intended for the tests to be included in the package built by the make release. 

This could be very useful because in some projects there are security requirements that  prohibit everything related to testing in a production environment

**Comment by moas** [comment]
May be add .releaseignore file like .gitignore

**Comment by thefab** [comment]
yes good idea (and we already have https://github.com/mherrmann/gitignore_parser in metwork) to parser gitignore like files

**Comment by thebaptiste** [comment]
Done (mostly in mfutil). To be merged.
