### ISSUE TITLE
XAttrfile/BytesDictWithDirtyFlag; get function failed if the key doesn't exit even is the default parameter value is set

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfdata#350]
I'm using xaf.tags.get(key, default_value) function as mentionned in the exemple [switch_rules:python] : http://metwork-framework.org/pub/metwork/releases/docs/release_1.0/mfdata/500-switch_rules/#38-python

e.g. 
magic = xaf.tags.get('latest.switch.main.system_magic', None)

So magic variable is supposed to be None if the key doesn't exist. But when the key doesn't exist, the function failed :

```
2020-10-30T15:37:49.334496Z    [ERROR] (switch/rules#31580) exception during rule block <acquisition.switch_rules.PythonRulesBlock object at 0x7f6fadccfbe0> eval on /home/dearith10/metwork/mfdata/var/plugins/foo:switch_rules.rule
Traceback (most recent call last):
  File "/opt/metwork-mfext-1.0/opt/python3/lib/python3.7/site-packages/acquisition/switch_rules.py", line 83, in evaluate
    res = self.eval(xaf, rule.pattern)
  File "/opt/metwork-mfext-1.0/opt/python3/lib/python3.7/site-packages/acquisition/switch_rules.py", line 204, in eval
    res = func(xaf)
  File "/home/dearith10/metwork/mfdata/var/plugins/foo/switch_rules.py", line 10, in rule
    magic = xaf.tags.get('latest.switch.main.system_magic', None)
  File "/opt/metwork-mfext-1.0/opt/python3/lib/python3.7/site-packages/xattrfile/__init__.py", line 135, in __getitem__
    return super(BytesDictWithDirtyFlag, self).__getitem__(new_key)
KeyError: b'latest.switch.main.system_magic'
```

Additional question : in switch_rules function, is there any way to log somewhere for debugging. I' mtrying to use print or using logger(switch/rules) but it doesn't work.

Thanks

**Comment by thefab** [comment]
```

**Comment by thefab** [comment]
note: logging or print in switch python functions works but the output is in the `switch` log file (not in your plugin one)

**Comment by thefab** [comment]
I can't reproduce this:

```

**Comment by thefab** [comment]
@dearith some additional details?

**Comment by dearith** [comment]
@thefab Yes I'm trying to reproduce the issue (I changed my code because of this issue).

About log and print, I use print function like you, but there is no print in the switch log file. Perhaps, I make a mistake, I'm going to try again.

How to use logger : something like this ?
LOGGER = mflog.getlogger("switch/rules")

LOGGER.info(....)

I notice the debug mode = 0 of the switch, and if I want debug = 1 , I have to override by setting switch.ini in the /etc/metwork.config.d/mfdata/external_plugins ? Is it right.

**Comment by dearith** [comment]
@thefab . I can't no longer reproduce the issue. I run the same code I wrote last week, and now it works (also print and log)  
```
"""
switch rule implementation
"""
from mflog import get_logger

LOGGER = get_logger("switch/rules")

def rule(xaf):
    magic_ok = xaf.tags.get('latest.switch.main.system_magic', 'empty').startswith('ASCII text')
    print(f"magic OK {magic_ok}")
    LOGGER.info(f"magic2 OK {magic_ok}")
    not_ingestion_subject = b'latest.amqp_subscriber.listener.ingestion_subject' not in xaf.tags.keys()
    if magic_ok and not_ingestion_subject:
        return True

    return False
```


Very strange.  So, I think you can cancel this issue.
