### ISSUE TITLE
ungzip plugin (Metwork 0.x) vs try_ungzip (or ungzip) decorators : something went wrong in the workflow

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfdata#365]
During the migration of MFDATA Metwork 0.9 plugins to Metwork 1.0, I am facing a issue:

With  **Metwork 0.x**, we develop  a plugin that accepts only xml files, with switch logical condition based on the magic file (in the plugin directory) and the magic tags . In Metwork 0.x, there is the ungzip plugin that uncompress a gz file and reinjects it to the switch plugin (i.e the xml file) (as desribed in a Metwork 0.x tutorials : https://metwork-framework.org/pub/metwork/continuous_integration/docs/integration/mfdata/950-old_docs/mfdata_additional_tutorials/#1-a-png-to-jpeg-conversion-plugin)

In the ingestion process, the product (file) to ingest  is either an xml file or a gz file that contains the xml file.

All works fine, if it's a gz file, my plugin received the xml file contained in the gz file thanks to the ungzip process/workflow

Now, with **Metwork 1.0**, this use case doesn't work anymore (or at lesat, with the decorators) :

the ungzip plugin is not installed (by default), so I use the try_ungzip decorator on the process function to uncompressed file. That's great, but.... in my case, the plugin doesn't work anymore, because the switch (or guess_file_type) plugin, never received the uncompressed file (i.e the xml file), and the magic tags are : latest.guess_file_type.main.system_magic = gzip compressed data (for the system magic) and latest.guess_file_type.main.custom_magic = data (for the custom tag). They doesn't match to the XML file (described in my magin custom file). It seems 'normal', because with decorators the uncompress process is done when the plugin received the file and before processing it

Note : I configured the guess_file_type with my custom magic file, e.g.: `guess_file_type.ini ` in `/etc/metwork.config.d/mfdata/plugins`

```
[step_main]
debug=1

[custom]

# Custom libmagic configuration file
# (empty => no custom magic configuration file, default "system" configuration
#           file will be used)
# (see http://man7.org/linux/man-pages/man4/magic.4.html)
magic_custom_file = /etc/metwork.config.d/mfdata/plugins/magic_custom_metgate
```

In my opinion, in order to resolve this issue, I have to install ungzip plugin in mfdata (e.g. add in mfdata config.ini `install_ungzip=1` in the ` [internal_plugins] ` section, and remove the try_ungzip decorators from the plugin code.

Am I right ? Is there another solution ?

**Comment by thefab** [comment]
yes:
- I think you need the `ungzip` plugin

no:
- dont add `install_ungzip=1`in `[internal_plugins]` (like with metwork 0.x) because the `ungzip`plugin is not system wide anymore

so:
- install your instance of ungzip plugin with `plugins.install --new-name=myungzip /opt/metwork-mfdata-1.0/share/plugins/ungzip-....plugin`
- configure your instance in `~/config/plugins/myungzip.ini` 
    - switch rules are by default "gzip compressed data*" on latest.guess_file_type.main.system_magic which is probably a good start but you can be more specific as this plugin is dedicated to your usage
    - default dest_dir (custom section) is to give the file back to guess_file_type (like metwork 0.x) but also you can be more specific to target directly your other plugin
- (optionally) you can repackage your configuration change (with lpugins.repackage)
- the myungzip plugin is now under your responsability (you have to deliver it with your business package)

**Comment by dearith** [comment]
Ok. Thanks for your advice.
