### ISSUE TITLE
Switch plugin - switch_no_match_policy=keep doesn't work

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfdata#65]
Hi,

If we set switch_no_match_policy=keep, the file is not kept in the trash (var/in/trash)  and it is deleted (same as delete policy). 

Note : after changing policy,  I restart MFDATA service to reload the MFDATA configuration.

**Comment by thefab** [comment]
reproduced !

thanks !

**Comment by thefab** [comment]
if you want to hotfix it, here is the basic fix:

```
diff --git a/plugins/switch/main.py b/plugins/switch/main.py
index dd847cf..d1150f6 100755
--- a/plugins/switch/main.py
+++ b/plugins/switch/main.py
@@ -122,7 +122,7 @@ class AcquisitionSwitchStep(AcquisitionStep):
 
     def _no_match(self, xaf):
         self.info("No condition matched for %s" % xaf.filepath)
-        if self.no_match_policy == "trash":
+        if self.no_match_policy == "keep":
             new_filepath = \
                 os.path.join(_get_or_make_trash_dir(self.plugin_name,
                                                     self.step_name),
```

the file is in `/home/mfdata/var/plugins/switch/main.py`

I'm going to add some extra options for this mode (`--keep-tags` and `--keep-tags-suffix` like for `archive` plugins)
