### ISSUE TITLE
doc: fix "the corresponding document" link in "how to install" chapter

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfdata#79]

**Comment by thebaptiste** [comment]
I think the link is ok now ?

**Comment by matthieumarrast** [comment]
About link in the documentation, I just noticed the wikipedia link is wrong in page [http://metwork-framework.org/pub/metwork/releases/docs/stable/mfdata/mfdata_and_magic.html](http://metwork-framework.org/pub/metwork/releases/docs/stable/mfdata/mfdata_and_magic.html), the last parenthesis must be included in the link.
